package com.proyectofinal.batallanavalkt.models

import com.proyectofinal.batallanavalkt.R

//Clase para los jugadores
class Player() {
    private var nickname:String=""
    private var usermail :String=""
    private var ppt = -1 //piedra(0, pznave="", isnave = false, angle=0), papel(1) o tijera(2)
    private var isFirst = false
    private var autowin = false
    private val maxposition = 40;
    private var usetable = 0;
    private val naveslist:MutableList<Nave> = mutableListOf()
    private var mytable: MutableList<Cuadrante> = arrayListOf(
        Cuadrante(id= 1, name= "00", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 2, name= "01", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 3, name= "02", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 4, name= "03", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 5, name= "04", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 6, name= "05", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 7, name= "06", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 8, name= "07", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 9, name= "08", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 10, name= "09", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),
        Cuadrante(id= 11, name= "10", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 12, name= "11", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 13, name= "12", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 14, name= "13", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 15, name= "14", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 16, name= "15", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 17, name= "16", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 18, name= "17", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 19, name= "18", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 20, name= "19", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),
        Cuadrante(id= 21, name= "20", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 22, name= "21", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 23, name= "22", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 24, name= "23", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 25, name= "24", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 26, name= "25", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 27, name= "26", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 28, name= "27", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 29, name= "28", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 30, name= "29", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),
        Cuadrante(id= 31, name= "30", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 32, name= "31", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 33, name= "32", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 34, name= "33", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 35, name= "34", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 36, name= "35", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 37, name= "36", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 38, name= "37", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 39, name= "38", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 40, name= "39", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),
        Cuadrante(id= 41, name= "40", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 42, name= "41", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 43, name= "42", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 44, name= "43", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 45, name= "44", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 46, name= "45", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 47, name= "46", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 48, name= "47", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 49, name= "48", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 50, name= "49", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),
        Cuadrante(id= 51, name= "50", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 52, name= "51", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 53, name= "52", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 54, name= "53", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 55, name= "54", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 56, name= "55", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 57, name= "56", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 58, name= "57", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 59, name= "58", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 60, name= "59", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),
        Cuadrante(id= 61, name= "60", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 62, name= "61", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 63, name= "62", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 64, name= "63", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 65, name= "64", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 66, name= "65", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 67, name= "66", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 68, name= "67", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 69, name= "68", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 70, name= "69", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),
        Cuadrante(id= 71, name= "70", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 72, name= "71", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 73, name= "72", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 74, name= "73", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 75, name= "74", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 76, name= "75", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 77, name= "76", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 78, name= "77", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 79, name= "78", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 80, name= "79", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),
        Cuadrante(id= 81, name= "80", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 82, name= "81", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 83, name= "82", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 84, name= "83", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 85, name= "84", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 86, name= "85", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 87, name= "86", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 88, name= "87", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 89, name= "88", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 90, name= "89", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),
        Cuadrante(id= 91, name= "90", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 92, name= "91", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 93, name= "92", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 94, name= "93", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 95, name= "94", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 96, name= "95", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 97, name= "96", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 98, name= "97", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 99, name= "98", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0),Cuadrante(id= 100, name= "99", isenable = false,isMar= true,isImpactMar= false,isImpact= false, bg=0, pznave="", isnave = false, angle=0))


    private var cantPA = 0
    private var cantB = 0
    private var cantSB = 0
    private var cantC = 0
    private var cantL = 0

    //naves
    fun getcantPA():Int{return cantPA}
    fun setcantPA(cant: Int){this.cantPA=cant}
    fun getcantB():Int{return cantB}
    fun setcantB(cant: Int){this.cantB=cant}
    fun getcantSB():Int{return cantSB}
    fun setcantSB(cant: Int){this.cantSB=cant}
    fun getcantC():Int{return cantC}
    fun setcantC(cant: Int){this.cantC=cant}
    fun getcantL():Int{return cantL}
    fun setcantL(cant: Int){this.cantL=cant}

    //TABLERO
    fun getmaxposition():Int{return maxposition}
    fun getusetable():Int{return usetable}
    fun setusetable(cant: Int){this.usetable=cant}

    fun getNickname():String{return nickname}
    fun setNickname(nickname: String){this.nickname=nickname}
    fun getUsermail():String{return usermail}
    fun setUsermail(usermail: String){this.usermail=usermail}
    fun getPpt():Int{return ppt}
    fun setPpt(ppt:Int){this.ppt=ppt}
    fun getIsFirst():Boolean{return isFirst}
    fun setIsFirst(isFirst:Boolean){this.isFirst=isFirst}
    fun getautowin():Boolean{return autowin}
    fun setautowin(winer:Boolean){this.autowin=winer}

    fun getMyTablero(): MutableList<Cuadrante> {return mytable}
    fun setMyTablero(list:MutableList<Cuadrante>) {this.mytable=list}



}
